### PR TITLE
REPL Workflow doc

### PR DESCRIPTION
**Pull request by thiru**
Here's my first attempt at documenting how to setup a multi-REPL workflow.  I'm very open to feedback - too much detail, not enough, etc.?

### CODE REVIEW

**Comment by bhauman** [comment]
So ... this is a good start, but I'd prefer to make this document only about connecting the vim editor with fireplace to figwheel.main cljs repl.

This is about how to get eval in your editor and how to have REPLs that you work with.

This procedure is very different for Emacs, and cursive because they have REPLs inside the editor.

BTW I updated it so that 0.1.5-SNAPSHOT will allow you to use the new nREPL cmdline.

Which I think simplifies this greatly.

**Comment by thiru** [comment]
Ahh ok.. I though what we discussed on slack was to document a workflow where your editor is separated from distinct REPLs for Clojure and ClojureScript.

Yes I can make this vim-specific.  So should I pull out all the stuff about how to have different REPLs for Clojure and ClojureScript?  That will make the doc much smaller for sure.

I don't quite understand how your nREPL cmdline fits in here.  I don't see it documented anywhere.  (sorry I'm sure this is a noob question)

**Comment by bhauman** [comment]
No you should keep the stuff about how to have the different REPLs because you need that for working with VIM.  Emacs Cider and Cursive both start repls inside the editors. Emacs Cider and Cursive are both amazing once you learn how to use them.

See the nrepl.cmdline in the document below. I think you will find it helpful:
https://nrepl.readthedocs.io/en/latest/usage/

It will only work with 0.1.5-SNAPSHOT but I'll be deploying 0.1.5 soon.

**Comment by thiru** [comment]
Ok cool I checked out the link.  So I can start the nREPL server without leiningen like so:

`clojure -R:nREPL -m nrepl.cmdline --middleware "[cider.piggieback/wrap-cljs-repl]"`

But I can't seem to get it working in conjunction with rebel-readline.  In the above example if `figwheel.main/start "dev"` everything works ok.  But if I run `(rebel-readline.main/-main)` before starting figwheel I get the following errors when calling `(js/alert "hi")` and even my own funcs:

`CompilerException java.lang.RuntimeException: Unable to resolve symbol: say-hi in this context, compiling:(null:1:1)`

Regarding Emacs I did try it a few years ago when I was using Common Lisp but I didn't really like.  I just love vim's snappiness but especially it's model text editing.  I feel handicapped whenever I can't use it now..

**Comment by thiru** [comment]
Here's what I'm testing with: https://github.com/thiru/fullstack-clojure

**Comment by thiru** [comment]
Ughh.. and of course the new nrepl/nrepl isn't yet supported by vim-fireplace..  uphill battle man..

**Comment by bhauman** [comment]
Also I've got the REPLs started now now do I connect to them with fireplace.

**Comment by bhauman** [comment]
well I hate to say I'm having a horrible time installing vim-fireplace but "whoa nellie!" this is hard as heck.

**Comment by thiru** [comment]
Hmm.. to be hones I'm not 100% sure I don't have competing figwheel.main processes.  But I don't see how vim would be able to start another one..

vim-fireplace will automatically connect to localhost, with the port specified in the .nrepl-port file, on the next eval.

Yes it is.. almost making me think to try another editor just for Clojure.. :/

**Comment by bhauman** [comment]
I'm connected now and I lost syntax highlighting but I have eval in Clojure.

**Comment by thiru** [comment]
Hmm.. maybe you're right about the ClojureScript environment.  I'm seeing some strange behaviour.

**Comment by bhauman** [comment]
OK I added some features to `figwheel.main` so that you can use the `:Piggieback` command.

I'm using a project.clj for this to minimize confusion:

```clojure
(defproject fullstack "0.1"
  :description "Minimal sample full-stack Clojure/Script website"
  :dependencies [[org.clojure/clojure "1.9.0"]
                             [org.clojure/clojurescript "1.10.339"]]
  :plugins [[cider/cider-nrepl "0.18.0"]]
  :profiles {:dev
             {:dependencies [[org.clojure/clojurescript "1.10.339"]
                             [com.bhauman/figwheel-main "0.1.6-SNAPSHOT"]
                             [com.bhauman/rebel-readline-cljs "0.1.4"]
                             [org.clojure/tools.nrepl "0.2.13"]
                             [cider/piggieback "0.3.8"]]
              :resource-paths ["target"]
              :clean-targets ^{:protect false} ["target"]
              :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}}})
```

Then in the terminal:

```shell
$ lein repl
user=> (require 'figwheel.main)
user=> (figwheel.main {:mode :serve} "dev")
```

Now you can start a CLJS repl with `user=> (figwheel.main/cljs-repl "dev")` you can also quit back to the regular REPL.

Then in vim first connect to the started nREPL server, then in a cljs file

`:Piggieback (figwheel.main/repl-env "dev")`

This will be a repl into your browser.

It is possible to set this up so that you have a rebel-readline-cljs repl, you would have to start a nREPL server as you did before in a regular `clojure` REPL and then start figwheel.

I should be able to provide a working example.

**Comment by thiru** [comment]
Thank you it works!! :)

I will update the vim doc accordingly.

You mentioned during our talk yesterday that you'd prefer to have the simplest working solution for integrating Vim(-fireplace) with figwheel-main.  Would you like me to alter the doc and remove the CLI tools bit and just stick to Leiningen?  Or maybe just start with instructions on how to set things up with Leiningen, and in a later section describe how to use it with CLI tools?

**Comment by bhauman** [comment]
Probably a simple start with leiningen, and then we'll have an advanced section where you create your own nrepl server with all the right middleware and have rebel-readline working in Clojure and ClojureScript

**Comment by thiru** [comment]
I just updated the doc with a simple Leiningen setup.  Let me know if you have any feedback.  I'll add more sections for using the Clojure CLI and rebel readline shortly.l

**Comment by thiru** [comment]
Ok I got the advanced sections in there now.  It all seems to be working pretty good now.

But I'm getting an error when changing `.clj` files, using the advanced setup.  With the Leiningen setup there's no problem.  I'll file a separate bug for this.

I also updated my [fullstack-clojure](https://github.com/thiru/fullstack-clojure) project with the simple Leiningen setup (master branch).  The [rebel branch](https://github.com/thiru/fullstack-clojure/tree/rebel) has the advanced setup.

**Comment by bhauman** [comment]
OK I'm sorry I haven't gotten around to publishing this, I'm still wanting to write a few tutorials before I put this up.

**Comment by thiru** [comment]
Awesome thanks! (sorry for the late response.. been away from home the last few weeks with very limited connectivity)

It looks like you already made the change.  I also see the vim docs haven't been set to published.  If there's any other changes you'd like let me know.

**Pull request merged**
