### PR TITLE
fix#298 Detect file changes much faster

### PR DESCRIPTION
**Pull request by timothypratley**
In my testing this cuts out a 6 second delay for reloading

### CODE REVIEW

**Comment by timothypratley** [comment]
fixes #298

**Comment by bhauman** [comment]
Great I'll definitely check it out. 

The main thing I'm interested in is that this will work well on all current platforms.

Folks have had trouble in docker and reverted to polling, among other issues.  I seem to remember an issue with the latest version of OSX as well. But that's probably been fixed by now.

**Comment by timothypratley** [comment]
Hi Bruce!

I searched past issues for "polling" and discovered
https://github.com/kkruit/full-stack-clj-example
Which has a dockerized build process.

I've confirmed that reloading works great without polling using the following methodology:
1. cloned that repo
2. started docker
3. chmod +x docker-dev/start-clj.sh
4. docker-compose up
5. verified it starts up, when I edit a file it reloads
6. ctrl-c stop it
7. edited docker-compose.yml add added a volumn to clj: `- ../figwheel-main:/usr/figwheel-main`
8. updated deps.edn figwheel to `:local/root "/usr/figwheel-main"` which points to my branch
9. removed `:hawk-options` from dev.cljs.edn (as build fails otherwise due to spec check)
10. docker-compose up
11. observed that it was using the new version and was reloading like a champ

**Comment by bhauman** [comment]
Thanks for doing that! That’s super helpful.

I’ll merge this and deploy a snapshot

**Comment by timothypratley** [comment]
You're welcome 😃

**Pull request merged**
