### PR TITLE
copy fixes

### PR DESCRIPTION
**Pull request by thiru**
Mostly just fixing typos in documentation

### CODE REVIEW

**Comment by bhauman** [comment]
This is fantastic thank you! The help is much appreciated. I have lots to edit.

**Comment by thiru** [comment]
The least I can do.  Thank you for your awesome libs!

**Comment by thiru** [comment]
I've been rewriting the sole commit in my branch with new copy fixes as I read through your docs.  I noticed you haven't merged in this commit yet so I guess this is ok?  Apologies in advance if not (this is my first pull request).  If you'd rather me go about this another way, let me know.

**Comment by bhauman** [comment]
Using the same PR is fine :)

I'd prefer not to have the formatting in main.cljc and helper.cljc altered.  I like the original indenting pattern when using reader conditionals over a large span.

Also the edits in `doc/figwheel-main-options.md` and `docs/config-options.md` will be overwritten because they are generated from the content in `figwheel.main.schema.config`.

Thanks for this amazing effort!

**Comment by thiru** [comment]
Oops sorry about those inadvertent changes to `main.cljc` and `helper.cljc`.  It seems one (or more) of my vim plugins applied some auto-formatting (probably the parinfer plugin).  I undid these and the changes to `doc/figwheel-main-options.md` and `docs/config-options.md`.

I finished going through all the docs in figwheel-main yesterday so these are probably the last of the changes.

Happy to help :)

**Comment by bhauman** [comment]
Thanks! I sorry I missed your changes to `doc/figwheel-main-options.md` as I'd really like to have these.
These would go in the `src/figwheel/main/schema/config.clj` file

**Comment by thiru** [comment]
Ah right.  Will create a new pull request for that soon.  Thank goodness for git reflog!

**Pull request merged**
