### PR TITLE
Fix reload-clj-files

### PR DESCRIPTION
**Pull request by mikekap**
Previously setting this to false disabled reloading cljc files for cljs.

### CODE REVIEW

**Comment by bhauman** [comment]
Mike I just tested the original code and `:reload-clj-files false` does not load `clj` or `cljc` files.

**Comment by mikekap** [comment]
Thanks for the quick response! Cljc files were correctly ignored in clj. The issue is cljc files weren’t reloaded in the browser (I.e. the cljs recompile didn’t trigger since it’s part of the same hawk watcher).

**Comment by bhauman** [comment]
Gotcha

**Comment by bhauman** [comment]
Yeah so a map isn't a valid value for `:reload-clj-files`.  I'm trying to stay away from adding conveniences to the config and keep it simple.  

I see the error now and I've coded up a solution. Big thanks for pointing it out as there are some other subtle problems that I didn't notice before.

**Comment by mikekap** [comment]
Awesome - thanks Bruce!

**Pull request closed without merging**
